server: 
  port: 9527
   
spring:
  application:
    name: miroservicecloud-zuul-gateway
  
eureka: 
  client: 
    service-url:   
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com   #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示IP地址
    
zuul: 
  # prefix: /zzf
  # ignored-services: "*" #忽略所有微服务时使用，多个用“,”隔开
  # ignored-services: miroservicecloud-dept
  routes: 
    mydept.serviceId: miroservicecloud-dept
    mydept.path:  /mydept/**
    
info: 
  app.name: zzf-miroservicecloud
  company.name: zzf.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$