server: 
  port: 3344
   
spring:
  application:
    name: miroservicecloud-config
  cloud:  
    config: 
      server:
        git:  
          uri:  git@github.com:fu7407/miroservicecloud-config.git #GitHub上面的git仓库的名字